"""Fetch OpenAlex taxonomy and generate local JSON seed file."""
import json
import urllib.request
from pathlib import Path

ZH_MAP = {
    "Agricultural and Biological Sciences": "农业与生物科学",
    "Arts and Humanities": "艺术与人文",
    "Biochemistry, Genetics and Molecular Biology": "生物化学、遗传学与分子生物学",
    "Business, Management and Accounting": "商学、管理学与会计学",
    "Chemical Engineering": "化学工程",
    "Chemistry": "化学",
    "Computer Science": "计算机科学",
    "Decision Sciences": "决策科学",
    "Earth and Planetary Sciences": "地球与行星科学",
    "Economics, Econometrics and Finance": "经济学、计量经济学与金融学",
    "Energy": "能源",
    "Engineering": "工程学",
    "Environmental Science": "环境科学",
    "Immunology and Microbiology": "免疫学与微生物学",
    "Materials Science": "材料科学",
    "Mathematics": "数学",
    "Medicine": "医学",
    "Neuroscience": "神经科学",
    "Nursing": "护理学",
    "Pharmacology, Toxicology and Pharmaceutics": "药理学、毒理学与药学",
    "Physics and Astronomy": "物理学与天文学",
    "Psychology": "心理学",
    "Social Sciences": "社会科学",
    "Veterinary": "兽医学",
    "Dentistry": "牙科学",
    "Health Professions": "健康专业",
}

SUBFIELD_ZH = {
    "History": "历史学",
    "Philosophy": "哲学",
    "Language and Linguistics": "语言与语言学",
    "Literature and Literary Theory": "文学与文学理论",
    "Visual Arts and Performing Arts": "视觉艺术与表演艺术",
    "Music": "音乐",
    "Religious studies": "宗教学",
    "Classics": "古典学",
    "Archeology": "考古学",
    "Conservation": "文物保护",
    "Museology": "博物馆学",
    "History and Philosophy of Science": "科学史与科学哲学",
    "Artificial Intelligence": "人工智能",
    "Computational Theory and Mathematics": "计算理论与数学",
    "Computer Networks and Communications": "计算机网络与通信",
    "Computer Science Applications": "计算机科学应用",
    "Computer Vision and Pattern Recognition": "计算机视觉与模式识别",
    "Hardware and Architecture": "硬件与架构",
    "Human-Computer Interaction": "人机交互",
    "Information Systems": "信息系统",
    "Signal Processing": "信号处理",
    "Software": "软件工程",
    "Computer Graphics and Computer-Aided Design": "计算机图形学与CAD",
    "Education": "教育学",
    "Law": "法学",
    "Sociology and Political Science": "社会学与政治学",
    "Political Science and International Relations": "政治学与国际关系",
    "Linguistics and Language": "语言学与语言",
    "Anthropology": "人类学",
    "Communication": "传播学",
    "Cultural Studies": "文化研究",
    "Gender Studies": "性别研究",
    "Demography": "人口学",
    "Urban Studies": "城市研究",
    "Public Administration": "公共管理",
    "Geography, Planning and Development": "地理、规划与发展",
    "Development": "发展研究",
    "Library and Information Sciences": "图书馆与信息科学",
    "Ecology, Evolution, Behavior and Systematics": "生态学、进化与系统学",
    "Genetics": "遗传学",
    "Epidemiology": "流行病学",
    "Neurology": "神经病学",
    "Oncology": "肿瘤学",
    "Cardiology and Cardiovascular Medicine": "心脏病学与心血管医学",
    "Surgery": "外科学",
    "Psychiatry and Mental health": "精神病学与心理健康",
    "Public Health, Environmental and Occupational Health": "公共卫生",
    "Anatomy": "解剖学",
    "Biochemistry": "生物化学",
    "Pharmacology": "药理学",
    "Physiology": "生理学",
    "Radiology, Nuclear Medicine and Imaging": "放射学与影像学",
    "Condensed Matter Physics": "凝聚态物理",
    "Astronomy and Astrophysics": "天文学与天体物理",
    "Nuclear and High Energy Physics": "核物理与高能物理",
    "Atomic and Molecular Physics, and Optics": "原子分子物理与光学",
    "Statistical and Nonlinear Physics": "统计与非线性物理",
    "Applied Mathematics": "应用数学",
    "Statistics and Probability": "统计与概率",
    "Algebra and Number Theory": "代数与数论",
    "Analysis": "分析",
    "Geometry and Topology": "几何与拓扑",
    "Discrete Mathematics and Combinatorics": "离散数学与组合数学",
    "Computational Mathematics": "计算数学",
    "Theoretical Computer Science": "理论计算机科学",
    "Logic": "逻辑学",
    "Modeling and Simulation": "建模与仿真",
    "Organic Chemistry": "有机化学",
    "Inorganic Chemistry": "无机化学",
    "Physical and Theoretical Chemistry": "物理与理论化学",
    "Analytical Chemistry": "分析化学",
    "Electrical and Electronic Engineering": "电气与电子工程",
    "Mechanical Engineering": "机械工程",
    "Civil and Structural Engineering": "土木与结构工程",
    "Biomedical Engineering": "生物医学工程",
    "Aerospace Engineering": "航空航天工程",
    "Industrial and Manufacturing Engineering": "工业与制造工程",
    "Control and Systems Engineering": "控制与系统工程",
    "Agronomy and Crop Science": "农学与作物科学",
    "Food Science": "食品科学",
    "Plant Science": "植物科学",
    "Animal Science and Zoology": "动物科学与动物学",
    "Aquatic Science": "水产科学",
    "Soil Science": "土壤科学",
    "Forestry": "林学",
    "Endocrinology, Diabetes and Metabolism": "内分泌学",
    "Hematology": "血液学",
    "Infectious Diseases": "传染病学",
    "Internal Medicine": "内科学",
    "Pediatrics, Perinatology and Child Health": "儿科学",
    "Dermatology": "皮肤科学",
    "Gastroenterology": "消化病学",
    "Ophthalmology": "眼科学",
    "Pathology and Forensic Medicine": "病理学与法医学",
    "Rehabilitation": "康复医学",
    "Materials Chemistry": "材料化学",
    "Polymers and Plastics": "聚合物与塑料",
    "Metals and Alloys": "金属与合金",
    "Ceramics and Composites": "陶瓷与复合材料",
    "Electronic, Optical and Magnetic Materials": "电子光学与磁性材料",
    "Biomaterials": "生物材料",
    "Environmental Chemistry": "环境化学",
    "Ecology": "生态学",
    "Environmental Engineering": "环境工程",
    "Waste Management and Disposal": "废物管理",
    "Water Science and Technology": "水科学与技术",
    "Renewable Energy, Sustainability and the Environment": "可再生能源与可持续发展",
    "Fuel Technology": "燃料技术",
    "Energy Engineering and Power Technology": "能源工程与动力技术",
    "Nuclear Energy and Engineering": "核能与核工程",
    "Geology": "地质学",
    "Geochemistry and Petrology": "地球化学与岩石学",
    "Oceanography": "海洋学",
    "Atmospheric Science": "大气科学",
    "Geophysics": "地球物理学",
    "Paleontology": "古生物学",
    "Space and Planetary Science": "空间与行星科学",
    "Immunology": "免疫学",
    "Microbiology": "微生物学",
    "Virology": "病毒学",
    "Parasitology": "寄生虫学",
    "Cellular and Molecular Neuroscience": "细胞与分子神经科学",
    "Cognitive Neuroscience": "认知神经科学",
    "Behavioral Neuroscience": "行为神经科学",
    "Developmental Neuroscience": "发育神经科学",
    "Sensory Systems": "感觉系统",
    "Social Psychology": "社会心理学",
    "Clinical Psychology": "临床心理学",
    "Developmental and Educational Psychology": "发展与教育心理学",
    "Experimental and Cognitive Psychology": "实验与认知心理学",
    "Applied Psychology": "应用心理学",
    "Neuropsychology and Physiological Psychology": "神经心理学与生理心理学",
    "Accounting": "会计学",
    "Finance": "金融学",
    "Marketing": "市场营销",
    "Strategy and Management": "战略与管理",
    "Organizational Behavior and Human Resource Management": "组织行为与人力资源管理",
    "Management of Technology and Innovation": "技术与创新管理",
    "Tourism, Leisure and Hospitality Management": "旅游休闲管理",
    "Economics and Econometrics": "经济学与计量经济学",
    "Management Science and Operations Research": "管理科学与运筹学",
    "Information Systems and Management": "信息系统与管理",
    "Statistics, Probability and Uncertainty": "统计、概率与不确定性",
    "Acoustics and Ultrasonics": "声学与超声学",
    "Aging": "衰老",
    "Anesthesiology and Pain Medicine": "麻醉学与疼痛医学",
    "Applied Microbiology and Biotechnology": "应用微生物学与生物技术",
    "Architecture": "建筑学",
    "Automotive Engineering": "汽车工程",
    "Bioengineering": "生物工程",
    "Biological Psychiatry": "生物精神医学",
    "Biophysics": "生物物理学",
    "Biotechnology": "生物技术",
    "Building and Construction": "建筑与施工",
    "Business and International Management": "商务与国际管理",
    "Cancer Research": "癌症研究",
    "Catalysis": "催化",
    "Cell Biology": "细胞生物学",
    "Chemical Health and Safety": "化学健康与安全",
    "Chiropractics": "脊椎指压治疗",
    "Clinical Biochemistry": "临床生物化学",
    "Colloid and Surface Chemistry": "胶体与表面化学",
    "Community and Home Care": "社区与家庭护理",
    "Complementary and Manual Therapy": "补充与手法治疗",
    "Complementary and alternative medicine": "补充与替代医学",
    "Computational Mechanics": "计算力学",
    "Computers in Earth Sciences": "地球科学中的计算",
    "Critical Care and Intensive Care Medicine": "重症医学",
    "Developmental Biology": "发育生物学",
    "Drug Discovery": "药物发现",
    "Earth-Surface Processes": "地表过程",
    "Ecological Modeling": "生态建模",
    "Electrochemistry": "电化学",
    "Emergency Medical Services": "急救服务",
    "Emergency Medicine": "急诊医学",
    "Endocrine and Autonomic Systems": "内分泌与自主神经系统",
    "Endocrinology": "内分泌学",
    "Equine": "马科动物",
    "Family Practice": "家庭医学",
    "Filtration and Separation": "过滤与分离",
    "Fluid Flow and Transfer Processes": "流体流动与传递过程",
    "Food Animals": "食用动物",
    "General Agricultural and Biological Sciences": "综合农业与生物科学",
    "General Arts and Humanities": "综合艺术与人文",
    "General Biochemistry, Genetics and Molecular Biology": "综合生化遗传与分子生物学",
    "General Business, Management and Accounting": "综合商学",
    "General Chemical Engineering": "综合化学工程",
    "General Chemistry": "综合化学",
    "General Decision Sciences": "综合决策科学",
    "General Dentistry": "综合牙科学",
    "General Earth and Planetary Sciences": "综合地球与行星科学",
    "General Economics, Econometrics and Finance": "综合经济与金融",
    "General Energy": "综合能源",
    "General Engineering": "综合工程",
    "General Environmental Science": "综合环境科学",
    "General Health Professions": "综合健康专业",
    "General Immunology and Microbiology": "综合免疫学与微生物学",
    "General Materials Science": "综合材料科学",
    "General Mathematics": "综合数学",
    "General Medicine": "综合医学",
    "General Neuroscience": "综合神经科学",
    "General Nursing": "综合护理学",
    "General Pharmacology, Toxicology and Pharmaceutics": "综合药理学、毒理学与药学",
    "General Physics and Astronomy": "综合物理与天文",
    "General Psychology": "综合心理学",
    "General Social Sciences": "综合社会科学",
    "General Veterinary": "综合兽医学",
    "Geriatrics and Gerontology": "老年医学",
    "Global and Planetary Change": "全球与行星变化",
    "Health": "健康（社会科学）",
    "Health Informatics": "健康信息学",
    "Health Information Management": "健康信息管理",
    "Health, Toxicology and Mutagenesis": "健康、毒理学与致突变",
    "Hepatology": "肝脏病学",
    "Horticulture": "园艺学",
    "Human Factors and Ergonomics": "人因工程学",
    "Immunology and Allergy": "免疫学与过敏学",
    "Industrial Relations": "劳资关系",
    "Industrial relations": "劳资关系",
    "Insect Science": "昆虫学",
    "Instrumentation": "仪器科学",
    "Issues, ethics and legal aspects": "议题、伦理与法律问题",
    "Leadership and Management": "领导力与管理",
    "Life-span and Life-course Studies": "生命历程研究",
    "Management Information Systems": "管理信息系统",
    "Management, Monitoring, Policy and Law": "管理、监测、政策与法律",
    "Mathematical Physics": "数学物理",
    "Maternity and Midwifery": "产科与助产学",
    "Mechanics of Materials": "材料力学",
    "Media Technology": "媒体技术",
    "Medical Assisting and Transcription": "医疗辅助",
    "Medical Laboratory Technology": "医学检验技术",
    "Medical Terminology": "医学术语",
    "Molecular Biology": "分子生物学",
    "Molecular Medicine": "分子医学",
    "Nature and Landscape Conservation": "自然与景观保护",
    "Nephrology": "肾脏病学",
    "Nurse Assisting": "护理辅助",
    "Numerical Analysis": "数值分析",
    "Nutrition and Dietetics": "营养与饮食学",
    "Obstetrics and Gynecology": "妇产科学",
    "Occupational Therapy": "职业治疗",
    "Ocean Engineering": "海洋工程",
    "Optometry": "视光学",
    "Oral Surgery": "口腔外科",
    "Orthodontics": "正畸学",
    "Orthopedics and Sports Medicine": "骨科与运动医学",
    "Otorhinolaryngology": "耳鼻喉科学",
    "Periodontics": "牙周病学",
    "Pharmaceutical Science": "药物科学",
    "Pharmacy": "药房学",
    "Physical Therapy, Sports Therapy and Rehabilitation": "物理治疗与康复",
    "Podiatry": "足病学",
    "Pollution": "污染研究",
    "Process Chemistry and Technology": "工艺化学与技术",
    "Psychiatric Mental Health": "精神健康护理",
    "Pulmonary and Respiratory Medicine": "肺病与呼吸医学",
    "Radiation": "辐射学",
    "Radiological and Ultrasound Technology": "放射与超声技术",
    "Reproductive Medicine": "生殖医学",
    "Research and Theory": "研究与理论",
    "Respiratory Care": "呼吸治疗",
    "Rheumatology": "风湿病学",
    "Safety Research": "安全研究",
    "Safety, Risk, Reliability and Quality": "安全、风险与质量",
    "Small Animals": "小型动物",
    "Spectroscopy": "光谱学",
    "Speech and Hearing": "言语与听力",
    "Stratigraphy": "地层学",
    "Structural Biology": "结构生物学",
    "Surfaces and Interfaces": "表面与界面",
    "Surfaces, Coatings and Films": "表面、涂层与薄膜",
    "Toxicology": "毒理学",
    "Transplantation": "移植学",
    "Transportation": "交通运输",
    "Urology": "泌尿科学",
}


def main():
    url = "https://api.openalex.org/fields?per_page=50"
    with urllib.request.urlopen(url) as r:
        data = json.loads(r.read())

    tree = []
    for f in data["results"]:
        field = {
            "name_en": f["display_name"],
            "name_zh": ZH_MAP.get(f["display_name"], ""),
            "openalex_id": f["id"].replace("https://openalex.org/", ""),
            "works_count": f.get("works_count"),
            "children": [],
        }
        for sf in f.get("subfields", []):
            sf_name = sf["display_name"]
            field["children"].append({
                "name_en": sf_name,
                "name_zh": SUBFIELD_ZH.get(sf_name, ""),
                "openalex_id": sf["id"].replace("https://openalex.org/", ""),
            })
        field["children"].sort(key=lambda x: x["name_en"])
        tree.append(field)

    DOMAIN_ORDER = {
        "Mathematics": 0,
        "Physics and Astronomy": 1,
        "Chemistry": 2,
        "Earth and Planetary Sciences": 3,
        "Environmental Science": 4,
        "Agricultural and Biological Sciences": 5,
        "Biochemistry, Genetics and Molecular Biology": 6,
        "Immunology and Microbiology": 7,
        "Neuroscience": 8,
        "Engineering": 9,
        "Chemical Engineering": 10,
        "Materials Science": 11,
        "Computer Science": 12,
        "Energy": 13,
        "Medicine": 14,
        "Pharmacology, Toxicology and Pharmaceutics": 15,
        "Nursing": 16,
        "Health Professions": 17,
        "Dentistry": 18,
        "Veterinary": 19,
        "Psychology": 20,
        "Social Sciences": 21,
        "Economics, Econometrics and Finance": 22,
        "Business, Management and Accounting": 23,
        "Decision Sciences": 24,
        "Arts and Humanities": 25,
    }
    tree.sort(key=lambda x: DOMAIN_ORDER.get(x["name_en"], 99))

    out_path = Path(__file__).parent.parent / "app" / "data" / "openalex_taxonomy.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as out:
        json.dump(tree, out, indent=2, ensure_ascii=False)

    total_sf = sum(len(f["children"]) for f in tree)
    print(f"Written {out_path}: {len(tree)} fields, {total_sf} subfields")


if __name__ == "__main__":
    main()
